
# dapr run --dapr-http-port 3500
# dapr run --app-id server --app-port 8080 node index.js
# dapr run --app-id service --app-port 3000 node service.js
POST http://localhost:3500/v1.0/invoke/service/method/add
content-type: application/json

{ "data": {"state": 0, "delta": 1,"id": "invoke" }}


###
#dapr publish --publish-app-id service --pubsub pubsub --topic add --data '{"data":[1,10],"id":"dapr"}'
POST http://localhost:3500/v1.0/publish/pubsub/add
content-type: application/json


{ "data": {"state": 0, "delta": 1,"id": "pubsub" }}
