
### REST
POST http://localhost:3500/v1.0/invoke/service/method/add
content-type: application/json

{"data": { "data": [1, 1], "wsid": "invoke", "event": "add" }}


### PUBSUB
POST http://localhost:3500/v1.0/publish/pubsub/add
content-type: application/json


{ "data": [1, 1], "wsid": "pubsub", "event": "add" }

### Message to WebSockets
POST http://localhost:3500/v1.0/publish/pubsub/ws
content-type: application/json


{ "data": 10, "wsid": "pubsub", "event": "add" }